kind: PersistentVolume
apiVersion: v1
metadata:
  name: bbb-nas
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: NAS-IP
    path: NFS-SHARE-PATH
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
