extraVolumes:
     - name: bbb-nas 
       persistentVolumeClaim:
           claimName: bbb-nas-claim  

extraVolumeMounts:
    - name: bbb-nas
      mountPath: /var/www/BBB/

replicaCount: 1

serverBlock: |-
  server {
    listen 0.0.0.0:8080;
        location /download {
          alias   /var/www/BBB/published;
          index  index.html index.htm;
          expires 1m;
        }
           location /playback/presentation/playback.html {
                return 301 /playback/presentation/0.81/playback.html?$query_string;
                # If you have recordings from 0.9.0 beta versions and are sure
                # that you will never want to play recordings made with
                # BigBlueButton 0.81, comment the line above and uncomment the
                # following line:
                #return 301 /playback/presentation/0.9.0/playback.html?$query_string;
           }

           location /playback/presentation {
                   root    /var/www/BBB;
                   index  index.html index.htm;
           }

           location /presentation {
                   root    /var/www/BBB/published;
                   index  index.html index.htm;
           }
  }
