apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-videos-pdb
  namespace: scalelite-ns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-videos
